version: '3.8'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432" #later comment this

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080