FROM golang:1.24-alpine3.21

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

#COPY cmd internal ./  # проблема с зависимостями 
# лишнее убирается в .dockerignore
COPY . .
# COPY cmd internal ./

RUN go build -v -o /usr/local/bin/app ./cmd/main.go && \
    adduser -D -g '' appuser

USER appuser

CMD ["app"]
